name: Lint
on: [push, pull_request]
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cppcheck clang-format
      - run: cppcheck --enable=warning,performance,portability --error-exitcode=1 .
